# Site settings
title: "Tech Junk Trunk"
email: adam@diginc.us
description: "Technical Junk Trunk Blog - Code, Automation, Learn"
baseurl: ""
url: "https://techjunktrunk.com/"
title_description: "Technical Junk in an empirical trunk"
#title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
title_image: "https://i.imgur.com/zKjBuan.jpg"
google_analytics: ""
#disqus_account: cartenoire
github_repository: https://github.com/diginc/tech-junk-trunk
addthis_id: 
post_limit: 5

# Social usernames/URLs
#twitter_username: 
github_username:  diginc
#instagram_username: 
reddit_username: diginc
#linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
#google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: https://stackoverflow.com/users/895792/diginc
#xing_link:
#facebook_link:

# Footer
footer_left: "Theme Carte Noire by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a> <i class=\"fa fa-heart\"></i>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/diginc/tech-junk-trunk\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
